/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/history/history` | `/history/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/settings` | `/settings/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/camera` | `/scanner/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/fact-check` | `/scanner/fact-check`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/highlight` | `/scanner/highlight`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/scannerScreen` | `/scanner/scannerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/history/history` | `/history/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings/settings` | `/settings/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scanner/camera` | `/scanner/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scanner/fact-check` | `/scanner/fact-check`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scanner/highlight` | `/scanner/highlight`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scanner/scannerScreen` | `/scanner/scannerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/history/history${`?${string}` | `#${string}` | ''}` | `/history/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings/settings${`?${string}` | `#${string}` | ''}` | `/settings/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scanner/camera${`?${string}` | `#${string}` | ''}` | `/scanner/camera${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scanner/fact-check${`?${string}` | `#${string}` | ''}` | `/scanner/fact-check${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scanner/highlight${`?${string}` | `#${string}` | ''}` | `/scanner/highlight${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scanner/scannerScreen${`?${string}` | `#${string}` | ''}` | `/scanner/scannerScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/history/history` | `/history/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/settings` | `/settings/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/camera` | `/scanner/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/fact-check` | `/scanner/fact-check`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/highlight` | `/scanner/highlight`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scanner/scannerScreen` | `/scanner/scannerScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
